/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDispositivosRouteImport } from './routes/_authenticated/dispositivos'
import { Route as AuthenticatedRevendedoresRouteImport } from './routes/_authenticated/revendedores'
import { Route as ApiPublicAuthRouteImport } from './routes/api/public/auth'
import { Route as ApiPublicMatchesRouteImport } from './routes/api/public/matches'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({ id: '/_authenticated', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedDispositivosRoute = AuthenticatedDispositivosRouteImport.update({ id: '/dispositivos', path: '/dispositivos', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedRevendedoresRoute = AuthenticatedRevendedoresRouteImport.update({ id: '/revendedores', path: '/revendedores', getParentRoute: () => AuthenticatedRouteRoute } as any)
const ApiPublicAuthRoute = ApiPublicAuthRouteImport.update({ id: '/api/public/auth', path: '/api/public/auth', getParentRoute: () => rootRouteImport } as any)
const ApiPublicMatchesRoute = ApiPublicMatchesRouteImport.update({ id: '/api/public/matches', path: '/api/public/matches', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispositivos': typeof AuthenticatedDispositivosRoute
  '/revendedores': typeof AuthenticatedRevendedoresRoute
  '/api/public/auth': typeof ApiPublicAuthRoute
  '/api/public/matches': typeof ApiPublicMatchesRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dispositivos': typeof AuthenticatedDispositivosRoute
  '/_authenticated/revendedores': typeof AuthenticatedRevendedoresRoute
  '/api/public/auth': typeof ApiPublicAuthRoute
  '/api/public/matches': typeof ApiPublicMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAuthRoute: typeof ApiPublicAuthRoute
  ApiPublicMatchesRoute: typeof ApiPublicMatchesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated': { id: '/_authenticated'; path: ''; fullPath: '/'; preLoaderRoute: typeof AuthenticatedRouteRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated/dashboard': { id: '/_authenticated/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof AuthenticatedDashboardRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/dispositivos': { id: '/_authenticated/dispositivos'; path: '/dispositivos'; fullPath: '/dispositivos'; preLoaderRoute: typeof AuthenticatedDispositivosRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/revendedores': { id: '/_authenticated/revendedores'; path: '/revendedores'; fullPath: '/revendedores'; preLoaderRoute: typeof AuthenticatedRevendedoresRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/api/public/auth': { id: '/api/public/auth'; path: '/api/public/auth'; fullPath: '/api/public/auth'; preLoaderRoute: typeof ApiPublicAuthRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/matches': { id: '/api/public/matches'; path: '/api/public/matches'; fullPath: '/api/public/matches'; preLoaderRoute: typeof ApiPublicMatchesRouteImport; parentRoute: typeof rootRouteImport }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDispositivosRoute: typeof AuthenticatedDispositivosRoute
  AuthenticatedRevendedoresRoute: typeof AuthenticatedRevendedoresRoute
}
const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute,
  AuthenticatedDispositivosRoute,
  AuthenticatedRevendedoresRoute,
}
const AuthenticatedRouteRouteWithChildren = AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute,
  ApiPublicAuthRoute,
  ApiPublicMatchesRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
